'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LangCode = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'ml';

export interface LangMeta {
  code: LangCode;
  label: string;
  name: string;
  flag: string;
}

export const LANGUAGES: LangMeta[] = [
  { code: 'en', label: 'EN', name: 'English', flag: '🇮🇳' },
  { code: 'hi', label: 'हि', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', label: 'த', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'తె', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', label: 'ಕ', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', label: 'മ', name: 'മലയാളം', flag: '🇮🇳' },
];

// ── Complete Translated UI strings for all supported languages ──────────────────
export const TRANSLATIONS: Record<LangCode, Record<string, string>> = {
  en: {
    // Navigation & Layout
    dashboard: 'Dashboard',
    analyzeReq: 'Analyze Requirement',
    tenderAnalyzer: 'Tender Analyzer',
    specAssistant: 'Spec Assistant',
    standardsExplorer: 'Standards Explorer',
    standardsGraph: 'Standards Graph',
    gapAnalysis: 'Gap Analysis',
    versionCheck: 'Version & Amendments',
    analysisHistory: 'Analysis History',
    searchPlaceholder: 'Search standards, products, tenders...',
    askIsSmart: 'Ask IS-SMART',
    systemStatus: 'SYSTEM STATUS',
    allOperational: 'All Systems Operational',

    // Hero Section
    aiStandardsIntel: 'AI-Powered Standards Intelligence',
    heroTitlePart1: 'Find the Right ',
    indianStandards: 'Indian Standards',
    heroTitlePart2: '. Build Better Tenders.',
    heroSubtitle: 'AI-powered assistance for identifying applicable Indian Standards, related requirements, certifications, amendments, and tender specification gaps.',
    describeProcurementDetail: 'Describe your procurement requirement in detail...',
    procurementPlaceholder: 'Describe your procurement requirement in detail... Example: Procure 500 stainless steel water storage tanks for government hospitals',
    uploadTenderDoc: 'Upload Tender Document',
    analyzeRequirement: 'Analyze Requirement',

    // Metric Cards
    standardsIndexed: 'Standards Indexed',
    acrossAllSectors: 'Across all sectors',
    relationshipsMapped: 'Relationships Mapped',
    standardsInterconnections: 'Standards interconnections',
    tendersAnalyzed: 'Tenders Analyzed',
    thisMonth: 'This month',
    issuesDetected: 'Issues Detected',
    potentialSpecGaps: 'Potential spec gaps',

    // Pipeline Flow
    aiAnalysisPipeline: 'AI Analysis Pipeline',
    viewFullPipeline: 'View Full Pipeline',
    stepInputRequirement: 'Input Requirement',
    stepAiAnalysis: 'AI Analysis',
    stepUnderstanding: 'Understanding',
    stepProductId: 'Product ID',
    stepIdentification: 'Identification',
    stepReqExtraction: 'Req Extraction',
    stepKeyParameters: 'Key Parameters',
    stepStandardsMatching: 'Standards Matching',
    stepAiMatching: 'AI Matching',
    stepRelationships: 'Relationships',
    stepMapping: 'Mapping',
    stepVersionCheck: 'Version Check',
    stepLatestVersions: 'Latest Versions',
    stepGapAnalysis: 'Gap Analysis',
    stepIssueDetection: 'Issue Detection',
    stepCertifications: 'Certifications',
    stepValidations: 'Validations',
    stepSpecGeneration: 'Spec Generation',
    stepOutput: 'Output',

    // Bottom Grid
    recentAnalyses: 'Recent Analyses',
    viewAll: 'View All',
    itemWaterTanks: 'Water Tanks',
    itemRccPipes: 'RCC Pipes',
    itemLedStreetLight: 'LED Street Light',
    timeToday: 'Today, 10:24 AM',
    timeYesterday: 'Yesterday',
    topStandardsByUsage: 'Top Standards by Usage',
    explore: 'Explore',
    issueSummary: 'Issue Summary',
    completed: 'Completed',
    totalIssues: 'TOTAL ISSUES',
    missing: 'Missing',
    outdated: 'Outdated',
    ambiguous: 'Ambiguous',
    certGaps: 'Cert Gaps',

    // Inputs & Forms
    product: 'Product / Service',
    productPlaceholder: 'e.g. Outdoor LED Street Light, Industrial Water Pump',
    purpose: 'Purpose / Application',
    purposePlaceholder: 'e.g. Highway street lighting for NH infrastructure project',
    techReq: 'Technical Requirements',
    techReqPlaceholder: 'Enter technical requirements, one per line:\nPower rating: 100W\nIP rating: IP65 or higher\nDesign life: 50,000 hours',
    environment: 'Operating Environment',
    envPlaceholder: 'e.g. Outdoor / Coastal / Monsoon conditions',
    industry: 'Industry / Sector',
    analyzeBtn: 'Analyze with AI',
    chatPlaceholder: 'Describe your requirement or ask about standards...',
    chatGreeting: "Hello! I'm the IS-SMART Procurement Assistant. I can help identify applicable Indian Standards for your procurement requirement. What product or equipment do you need standards for?",
    regionalNote: 'You can also type requirements in regional languages (Tamil, Hindi, Telugu, Kannada, Malayalam).',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    analyzeReq: 'आवश्यकता का विश्लेषण करें',
    tenderAnalyzer: 'निविदा विश्लेषक',
    specAssistant: 'विनिर्देश सहायक',
    standardsExplorer: 'मानक एक्सप्लोरर',
    standardsGraph: 'मानक ग्राफ',
    gapAnalysis: 'अंतर विश्लेषण',
    versionCheck: 'संस्करण और संशोधन',
    analysisHistory: 'विश्लेषण इतिहास',
    searchPlaceholder: 'मानक, उत्पाद, निविदाएं खोजें...',
    askIsSmart: 'IS-SMART से पूछें',
    systemStatus: 'सिस्टम स्थिति',
    allOperational: 'सभी प्रणालियां चालू हैं',
    aiStandardsIntel: 'एआई-संचालित भारतीय मानक इंटेलिजेंस',
    heroTitlePart1: 'सही ',
    indianStandards: 'भारतीय मानक',
    heroTitlePart2: ' खोजें। बेहतर निविदाएं बनाएं।',
    heroSubtitle: 'लागू भारतीय मानकों, संबंधित आवश्यकताओं, प्रमाणपत्रों, संशोधनों और निविदा विनिर्देश अंतरालों की पहचान के लिए एआई सहायता।',
    describeProcurementDetail: 'अपनी खरीद आवश्यकता का विस्तार से वर्णन करें...',
    procurementPlaceholder: 'अपनी खरीद आवश्यकता का विस्तार से वर्णन करें... उदाहरण: सरकारी अस्पतालों के लिए 500 स्टेनलेस स्टील पानी की टंकियां खरीदें',
    uploadTenderDoc: 'निविदा दस्तावेज अपलोड करें',
    analyzeRequirement: 'आवश्यकता का विश्लेषण करें',
    standardsIndexed: 'अनुक्रमित मानक',
    acrossAllSectors: 'सभी क्षेत्रों में',
    relationshipsMapped: 'मैप किए गए संबंध',
    standardsInterconnections: 'मानक अंतर्संबंध',
    tendersAnalyzed: 'विश्लेषित निविदाएं',
    thisMonth: 'इस महीने',
    issuesDetected: 'खोजे गए मुद्दे',
    potentialSpecGaps: 'संभावित विनिर्देश अंतराल',
    aiAnalysisPipeline: 'एआई विश्लेषण पाइपलाइन',
    viewFullPipeline: 'पूर्ण पाइपलाइन देखें',
    stepInputRequirement: 'आवश्यकता इनपुट',
    stepAiAnalysis: 'एआई विश्लेषण',
    stepUnderstanding: 'समझ',
    stepProductId: 'उत्पाद आईडी',
    stepIdentification: 'पहचान',
    stepReqExtraction: 'आवश्यकता निष्कर्षण',
    stepKeyParameters: 'मुख्य पैरामीटर',
    stepStandardsMatching: 'मानक मिलान',
    stepAiMatching: 'एआई मिलान',
    stepRelationships: 'संबंध',
    stepMapping: 'मैपिंग',
    stepVersionCheck: 'संस्करण जांच',
    stepLatestVersions: 'नवीनतम संस्करण',
    stepGapAnalysis: 'अंतर विश्लेषण',
    stepIssueDetection: 'मुद्दा पहचान',
    stepCertifications: 'प्रमाणन',
    stepValidations: 'सत्यापन',
    stepSpecGeneration: 'विनिर्देश निर्माण',
    stepOutput: 'आउटपुट',
    recentAnalyses: 'हाल के विश्लेषण',
    viewAll: 'सभी देखें',
    itemWaterTanks: 'पानी की टंकियां',
    itemRccPipes: 'आरसीसी पाइप',
    itemLedStreetLight: 'एलईडी स्ट्रीट लाइट',
    timeToday: 'आज, सुबह 10:24',
    timeYesterday: 'कल',
    topStandardsByUsage: 'उपयोग के अनुसार शीर्ष मानक',
    explore: 'खोजें',
    issueSummary: 'मुद्दा सारांश',
    completed: 'पूरा हुआ',
    totalIssues: 'कुल मुद्दे',
    missing: 'अनुपस्थित',
    outdated: 'पुराना',
    ambiguous: 'अस्पष्ट',
    certGaps: 'प्रमाणन अंतराल',
    product: 'उत्पाद / सेवा',
    productPlaceholder: 'उदा. आउटडोर LED स्ट्रीट लाइट, औद्योगिक जल पंप',
    purpose: 'उद्देश्य / अनुप्रयोग',
    purposePlaceholder: 'उदा. राष्ट्रीय राजमार्ग बुनियादी ढांचे के लिए सड़क प्रकाश',
    techReq: 'तकनीकी आवश्यकताएं',
    techReqPlaceholder: 'तकनीकी आवश्यकताएं दर्ज करें:\nबिजली रेटिंग: 100W\nआईपी रेटिंग: IP65 या अधिक\nडिज़ाइन जीवन: 50,000 घंटे',
    environment: 'परिचालन वातावरण',
    envPlaceholder: 'उदा. आउटडोर / तटीय / मानसून की स्थिति',
    industry: 'उद्योग / क्षेत्र',
    analyzeBtn: 'AI से विश्लेषण करें',
    chatPlaceholder: 'अपनी आवश्यकता बताएं या मानकों के बारे में पूछें...',
    chatGreeting: 'नमस्ते! मैं IS-SMART खरीद सहायक हूं। मैं आपकी खरीद आवश्यकता के लिए लागू भारतीय मानकों की पहचान करने में मदद कर सकता हूं। आपको किस उत्पाद के लिए मानकों की आवश्यकता है?',
    regionalNote: 'आप हिंदी, तमिल, तेलुगु, कन्नड़ या मलयालम में आवश्यकताएं भी टाइप कर सकते हैं।',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    analyzeReq: 'தேவையை ஆராயுங்கள்',
    tenderAnalyzer: 'டெண்டர் ஆய்வாளர்',
    specAssistant: 'குறிப்பீட்டு உதவியாளர்',
    standardsExplorer: 'தரநிலைகள் உலாவி',
    standardsGraph: 'தரநிலைகள் வரைபடம்',
    gapAnalysis: 'இடைவெளி பகுப்பாய்வு',
    versionCheck: 'பதிப்பு மற்றும் திருத்தங்கள்',
    analysisHistory: 'பகுப்பாய்வு வரலாறு',
    searchPlaceholder: 'தரநிலைகள், தயாரிப்புகளைத் தேடுங்கள்...',
    askIsSmart: 'IS-SMART இடம் கேளுங்கள்',
    systemStatus: 'அமைப்பு நிலை',
    allOperational: 'அனைத்து அமைப்புகளும் செயல்படுகின்றன',
    aiStandardsIntel: 'AI-இயங்கும் இந்திய தரநிலைகள் நுண்ணறிவு',
    heroTitlePart1: 'சரியான ',
    indianStandards: 'இந்திய தரநிலைகளை',
    heroTitlePart2: ' கண்டறியவும். சிறந்த டெண்டர்களை உருவாக்குங்கள்.',
    heroSubtitle: 'பொருந்தக்கூடிய இந்திய தரநிலைகள், சான்றிதழ்கள் மற்றும் விவரக்குறிப்பு இடைவெளிகளை கண்டறிய AI உதவி.',
    procurementPlaceholder: 'உங்கள் கொள்முதல் தேவையை விரிவாக விவரிக்கவும்... எ.கா: அரசு மருத்துவமனைகளுக்கு 500 துருப்பிடிக்காத எஃகு தண்ணீர் தொட்டிகள் வாங்கவும்',
    uploadTenderDoc: 'டெண்டர் ஆவணத்தைப் பதிவேற்றவும்',
    analyzeRequirement: 'தேவையை ஆராயுங்கள்',
    standardsIndexed: 'அடைவடைக்கப்பட்ட தரநிலைகள்',
    acrossAllSectors: 'அனைத்து துறைகளிலும்',
    relationshipsMapped: 'வரைபடமாக்கப்பட்ட உறவுகள்',
    standardsInterconnections: 'தரநிலைகள் இணைப்பு',
    tendersAnalyzed: 'பகுப்பாய்வு செய்யப்பட்ட டெண்டர்கள்',
    thisMonth: 'இந்த மாதம்',
    issuesDetected: 'கண்டறியப்பட்ட சிக்கல்கள்',
    potentialSpecGaps: 'சாத்தியமான விவரக்குறிப்பு இடைவெளிகள்',
    aiAnalysisPipeline: 'AI பகுப்பாய்வு பைப்லைன்',
    viewFullPipeline: 'முழு பைப்லைனையும் காண்க',
    stepInputRequirement: 'தேவை உள்ளீடு',
    stepAiAnalysis: 'AI பகுப்பாய்வு',
    stepUnderstanding: 'புரிதல்',
    stepProductId: 'தயாரிப்பு ஐடி',
    stepIdentification: 'அடையாளம்',
    stepReqExtraction: 'தேவை பிரித்தெடுத்தல்',
    stepKeyParameters: 'முக்கிய அளவுருக்கள்',
    stepStandardsMatching: 'தரநிலைகள் பொருத்தம்',
    stepAiMatching: 'AI பொருத்தம்',
    stepRelationships: 'உறவுகள்',
    stepMapping: 'வரைபடமாக்கல்',
    stepVersionCheck: 'பதிப்பு சரிபார்ப்பு',
    stepLatestVersions: 'சமீபத்திய பதிப்புகள்',
    stepGapAnalysis: 'இடைவெளி பகுப்பாய்வு',
    stepIssueDetection: 'சிக்கல் கண்டறிதல்',
    stepCertifications: 'சான்றிதழ்கள்',
    stepValidations: 'சரிபார்த்தல்',
    stepSpecGeneration: 'விவரக்குறிப்பு உருவாக்கம்',
    stepOutput: 'வெளியீடு',
    recentAnalyses: 'சமீபத்திய பகுப்பாய்வுகள்',
    viewAll: 'அனைத்தையும் காண்க',
    topStandardsByUsage: 'பயன்பாட்டின் அடிப்படையில் சிறந்த தரநிலைகள்',
    explore: 'ஆராயுங்கள்',
    issueSummary: 'சிக்கல் சுருக்கம்',
    completed: 'நிறைவடைந்தது',
    totalIssues: 'மொத்த சிக்கல்கள்',
    missing: 'காணவில்லை',
    outdated: 'பழையது',
    ambiguous: 'தெளிவற்றது',
    certGaps: 'சான்றிதழ் இடைவெளிகள்',
    product: 'தயாரிப்பு / சேவை',
    productPlaceholder: 'எ.கா. LED சாலை விளக்கு, தொழிற்துறை நீர் பம்ப்',
    purpose: 'நோக்கம் / பயன்பாடு',
    purposePlaceholder: 'எ.கா. தேசிய நெடுஞ்சாலை உள்கட்டமைப்பிற்கான சாலை விளக்கு',
    techReq: 'தொழில்நுட்ப தேவைகள்',
    techReqPlaceholder: 'தொழில்நுட்ப தேவைகளை உள்ளிடவும்:\nமின் திறன்: 100W\nIP மதிப்பீடு: IP65 அல்லது அதிகம்\nவடிவமைப்பு ஆயுள்: 50,000 மணி நேரம்',
    environment: 'இயக்க சூழல்',
    envPlaceholder: 'எ.கா. வெளிப்புற / கடலோர / மழைக்காலம்',
    industry: 'தொழில் / துறை',
    analyzeBtn: 'AI மூலம் பகுப்பாய்வு செய்யுங்கள்',
    chatPlaceholder: 'உங்கள் தேவையை விவரிக்கவும் அல்லது தரநிலைகளைப் பற்றி கேளுங்கள்...',
    chatGreeting: 'வணக்கம்! நான் IS-SMART கொள்முதல் உதவியாளர். உங்கள் தேவைகளுக்கு பொருந்தும் இந்திய தரநிலைகளை கண்டறிய உதவுவேன். எந்த தயாரிப்புக்கு தரநிலைகள் தேவை?',
    regionalNote: 'தமிழ், ஹிந்தி, தெலுங்கு, கன்னடம் அல்லது மலையாளத்திலும் உள்ளிடலாம்.',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    analyzeReq: 'అవసరాన్ని విశ్లేషించండి',
    tenderAnalyzer: 'టెండర్ అనలైజర్',
    specAssistant: 'స్పెసిఫికేషన్ అసిస్టెంట్',
    standardsExplorer: 'స్టాండర్డ్స్ ఎక్స్‌ప్లోరర్',
    standardsGraph: 'స్టాండర్డ్స్ గ్రాఫ్',
    gapAnalysis: 'గ్యాప్ అనాలిసిస్',
    versionCheck: 'వెర్షన్ & సవరణలు',
    analysisHistory: 'విశ్లేషణ చరిత్ర',
    searchPlaceholder: 'ప్రమాణాలు, ఉత్పత్తులను శోధించండి...',
    askIsSmart: 'IS-SMART ని అడగండి',
    systemStatus: 'సిస్టమ్ స్థితి',
    allOperational: 'అన్ని సిస్టమ్‌లు నడుస్తున్నాయి',
    aiStandardsIntel: 'AI-ఆధారిత భారతీయ ప్రమాణాల ఇంటెలిజెన్స్',
    heroTitlePart1: 'సరైన ',
    indianStandards: 'భారతీయ ప్రమాణాలను',
    heroTitlePart2: ' కనుగొనండి. మెరుగైన టెండర్లను నిర్మించండి.',
    heroSubtitle: 'వర్తించే భారతీయ ప్రమాణాలు, ధృవీకరణలు మరియు స్పెసిఫికేషన్ లోపాలను గుర్తించడానికి AI సహాయం.',
    procurementPlaceholder: 'మీ సేకరణ అవసరాన్ని వివరంగా వివరించండి... ఉదాహరణ: ప్రభుత్వ ఆసుపత్రుల కోసం 500 స్టెయిన్‌లెస్ స్టీల్ నీటి నిల్వ ట్యాంకులను కొనుగోలు చేయండి',
    uploadTenderDoc: 'టెండర్ పత్రాన్ని అప్‌లోడ్ చేయండి',
    analyzeRequirement: 'అవసరాన్ని విశ్లేషించండి',
    standardsIndexed: 'ఇండెక్స్ చేసిన ప్రమాణాలు',
    acrossAllSectors: 'అన్ని రంగాలలో',
    relationshipsMapped: 'మ్యాప్ చేసిన సంబంధాలు',
    standardsInterconnections: 'ప్రమాణాల అనుసంధానాలు',
    tendersAnalyzed: 'విశ్లేషించిన టెండర్లు',
    thisMonth: 'ఈ నెలలో',
    issuesDetected: 'గుర్తించిన సమస్యలు',
    potentialSpecGaps: 'సాధ్యమైన స్పెసిఫికేషన్ లోపాలు',
    aiAnalysisPipeline: 'AI విశ్లేషణ పైప్‌లైన్',
    viewFullPipeline: 'పూర్తి పైప్‌లైన్ చూడండి',
    stepInputRequirement: 'అవసరం ఇన్పుట్',
    stepAiAnalysis: 'AI విశ్లేషణ',
    stepUnderstanding: 'అవగాహన',
    stepProductId: 'ఉత్పత్తి ID',
    stepIdentification: 'గుర్తింపు',
    stepReqExtraction: 'అవసరం సేకరణ',
    stepKeyParameters: 'ముఖ్యమైన పారామితులు',
    stepStandardsMatching: 'ప్రమాణాల సరిపోలిక',
    stepAiMatching: 'AI సరిపోలిక',
    stepRelationships: 'సంబంధాలు',
    stepMapping: 'మ్యాపింగ్',
    stepVersionCheck: 'వెర్షన్ తనిఖీ',
    stepLatestVersions: 'తాజా వెర్షన్లు',
    stepGapAnalysis: 'గ్యాప్ విశ్లేషణ',
    stepIssueDetection: 'సమస్య గుర్తింపు',
    stepCertifications: 'సర్టిఫికేషన్లు',
    stepValidations: 'ధృవీకరణలు',
    stepSpecGeneration: 'స్పెసిఫికేషన్ రూపకల్పన',
    stepOutput: 'అవుట్‌పుట్',
    recentAnalyses: 'ఇటీవలి విశ్లేషణలు',
    viewAll: 'అన్నీ చూడండి',
    topStandardsByUsage: 'ఉపయోగం ప్రకారం అగ్ర ప్రమాణాలు',
    explore: 'అన్వేషించండి',
    issueSummary: 'సమస్యల సారాంశం',
    completed: 'పూర్తయింది',
    totalIssues: 'మొత్తం సమస్యలు',
    missing: 'లేవు',
    outdated: 'పాతవి',
    ambiguous: 'అస్పష్టం',
    certGaps: 'సర్టిఫికేషన్ లోపాలు',
    product: 'ఉత్పత్తి / సేవ',
    productPlaceholder: 'ఉదా. LED వీధి దీపాలు, పారిశ్రామిక నీటి పంప్',
    purpose: 'ఉద్దేశ్యం / అప్లికేషన్',
    purposePlaceholder: 'ఉదా. జాతీయ రహదారి మౌలిక సదుపాయాల కోసం రోడ్ లైటింగ్',
    techReq: 'సాంకేతిక అవసరాలు',
    techReqPlaceholder: 'సాంకేతిక అవసరాలను నమోదు చేయండి:\nశక్తి రేటింగ్: 100W\nIP రేటింగ్: IP65 లేదా అంతకంటే ఎక్కువ',
    environment: 'ఆపరేటింగ్ వాతావరణం',
    envPlaceholder: 'ఉదా. ఔట్‌డోర్ / తీర ప్రాంతం / వర్షాకాల పరిస్థితులు',
    industry: 'పరిశ్రమ / రంగం',
    analyzeBtn: 'AI తో విశ్లేషించండి',
    chatPlaceholder: 'మీ అవసరాన్ని వివరించండి లేదా ప్రమాణాల గురించి అడగండి...',
    chatGreeting: 'నమస్కారం! నేను IS-SMART సేకరణ సహాయకుడు. మీ అవసరాలకు వర్తించే భారతీయ ప్రమాణాలను గుర్తించడంలో సహాయపడతాను.',
    regionalNote: 'తెలుగు, హిందీ, తమిళం, కన్నడ లేదా మలయాళంలో కూడా నమోదు చేయవచ్చు.',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    analyzeReq: 'ಅವಶ್ಯಕತೆ ವಿಶ್ಲೇಷಿಸಿ',
    tenderAnalyzer: 'ಟೆಂಡರ್ ವಿಶ್ಲೇಷಕ',
    specAssistant: 'ಸ್ಪೆಸಿಫಿಕೇಶನ್ ಸಹಾಯಕ',
    standardsExplorer: 'ಮಾನದಂಡಗಳ ಎಕ್ಸ್‌ಪ್ಲೋರರ್',
    standardsGraph: 'ಮಾನದಂಡಗಳ ಗ್ರಾಫ್',
    gapAnalysis: 'ಗ್ಯಾಪ್ ವಿಶ್ಲೇಷಣೆ',
    versionCheck: 'ಆವೃತ್ತಿ ಮತ್ತು ತಿದ್ದುಪಡಿಗಳು',
    analysisHistory: 'ವಿಶ್ಲೇಷಣೆ ಇತಿಹಾಸ',
    searchPlaceholder: 'ಮಾನದಂಡಗಳು, ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...',
    askIsSmart: 'IS-SMART ಕೇಳಿ',
    systemStatus: 'ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ',
    allOperational: 'ಎಲ್ಲಾ ಸಿಸ್ಟಮ್‌ಗಳು ಕಾರ್ಯಾಚರಣೆಯಲ್ಲಿವೆ',
    aiStandardsIntel: 'AI-ಚಾಲಿತ ಭಾರತೀಯ ಮಾನದಂಡಗಳ ಇಂಟೆಲಿಜೆನ್ಸ್',
    heroTitlePart1: 'ಸರಿಯಾದ ',
    indianStandards: 'ಭಾರತೀಯ ಮಾನದಂಡಗಳನ್ನು',
    heroTitlePart2: ' ಕಂಡುಕೊಳ್ಳಿ. ಉತ್ತಮ ಟೆಂಡರ್‌ಗಳನ್ನು ನಿರ್ಮಿಸಿ.',
    heroSubtitle: 'ಅನ್ವಯವಾಗುವ ಭಾರತೀಯ ಮಾನದಂಡಗಳು, ಪ್ರಮಾಣಪತ್ರಗಳು ಮತ್ತು ವಿವರಣೆ ಕೊರತೆಗಳನ್ನು ಗುರುತಿಸಲು AI ನೆರವು.',
    procurementPlaceholder: 'ನಿಮ್ಮ ಖರೀದಿ ಅವಶ್ಯಕತೆಯನ್ನು ವಿವರವಾಗಿ ವಿವರಿಸಿ... ಉದಾಹರಣೆಗೆ: ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆಗಳಿಗೆ 500 ಸ್ಟೇನ್‌ಲೆಸ್ ಸ್ಟೀಲ್ ನೀರಿನ ಟ್ಯಾಂಕ್‌ಗಳನ್ನು ಖರೀದಿಸಿ',
    uploadTenderDoc: 'ಟೆಂಡರ್ ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    analyzeRequirement: 'ಅವಶ್ಯಕತೆ ವಿಶ್ಲೇಷಿಸಿ',
    standardsIndexed: 'ಸೂಚ್ಯಂಕಿತ ಮಾನದಂಡಗಳು',
    acrossAllSectors: 'ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ',
    relationshipsMapped: 'ಮ್ಯಾಪ್ ಮಾಡಿದ ಸಂಬಂಧಗಳು',
    standardsInterconnections: 'ಮಾನದಂಡಗಳ ಸಂಪರ್ಕಗಳು',
    tendersAnalyzed: 'ವಿಶ್ಲೇಷಿಸಿದ ಟೆಂಡರ್‌ಗಳು',
    thisMonth: 'ಈ ತಿಂಗಳು',
    issuesDetected: 'ಗುರುತಿಸಲಾದ ಸಮಸ್ಯೆಗಳು',
    potentialSpecGaps: 'ಸಂಭಾವ್ಯ ವಿವರಣೆ ಕೊರತೆಗಳು',
    aiAnalysisPipeline: 'AI ವಿಶ್ಲೇಷಣೆ ಪೈಪ್‌ಲೈನ್',
    viewFullPipeline: 'ಸಂಪೂರ್ಣ ಪೈಪ್‌ಲೈನ್ ವೀಕ್ಷಿಸಿ',
    stepInputRequirement: 'ಅವಶ್ಯಕತೆ ಇನ್‌ಪುಟ್',
    stepAiAnalysis: 'AI ವಿಶ್ಲೇಷಣೆ',
    stepUnderstanding: 'ಗ್ರಹಿಕೆ',
    stepProductId: 'ಉತ್ಪನ್ನ ID',
    stepIdentification: 'ಗುರುತಿಸುವಿಕೆ',
    stepReqExtraction: 'ಅವಶ್ಯಕತೆ ಹೊರತೆಗೆಯುವಿಕೆ',
    stepKeyParameters: 'ಪ್ರಮುಖ ನಿಯತಾಂಕಗಳು',
    stepStandardsMatching: 'ಮಾನದಂಡಗಳ ಹೋಲಿಕೆ',
    stepAiMatching: 'AI ಹೋಲಿಕೆ',
    stepRelationships: 'ಸಂಬಂಧಗಳು',
    stepMapping: 'ಮ್ಯಾಪಿಂಗ್',
    stepVersionCheck: 'ಆವೃತ್ತಿ ತಪಾಸಣೆ',
    stepLatestVersions: 'ಇತ್ತೀಚಿನ ಆವೃತ್ತಿಗಳು',
    stepGapAnalysis: 'ಗ್ಯಾಪ್ ವಿಶ್ಲೇಷಣೆ',
    stepIssueDetection: 'ಸಮಸ್ಯೆ ಪತ್ತೆ',
    stepCertifications: 'ಪ್ರಮಾಣೀಕರಣಗಳು',
    stepValidations: 'ದೃಢೀಕರಣಗಳು',
    stepSpecGeneration: 'ವಿವರಣೆ ರಚನೆ',
    stepOutput: 'ಔಟ್‌ಪುಟ್',
    recentAnalyses: 'ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆಗಳು',
    viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    topStandardsByUsage: 'ಬಳಕೆಯ ಆಧಾರದ ಮೇಲೆ ಪ್ರಮುಖ ಮಾನದಂಡಗಳು',
    explore: 'ಅನ್ವೇಷಿಸಿ',
    issueSummary: 'ಸಮಸ್ಯೆಗಳ ಸಾರಾಂಶ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    totalIssues: 'ಒಟ್ಟು ಸಮಸ್ಯೆಗಳು',
    missing: 'ಕಾಣೆಯಾಗಿದೆ',
    outdated: 'ಹಳೆಯದು',
    ambiguous: 'ಅಸ್ಪಷ್ಟ',
    certGaps: 'ಪ್ರಮಾಣೀಕರಣ ಕೊರತೆಗಳು',
    product: 'ಉತ್ಪನ್ನ / ಸೇವೆ',
    productPlaceholder: 'ಉದಾ. LED ಬೀದಿ ದೀಪ, ಕೈಗಾರಿಕಾ ನೀರಿನ ಪಂಪ್',
    purpose: 'ಉದ್ದೇಶ / ಅಪ್ಲಿಕೇಶನ್',
    purposePlaceholder: 'ಉದಾ. ರಾಷ್ಟ್ರೀಯ ಹೆದ್ದಾರಿ ಮೂಲಸೌಕರ್ಯಕ್ಕಾಗಿ ರಸ್ತೆ ಬೆಳಕು',
    techReq: 'ತಾಂತ್ರಿಕ ಅವಶ್ಯಕತೆಗಳು',
    techReqPlaceholder: 'ತಾಂತ್ರಿಕ ಅವಶ್ಯಕತೆಗಳನ್ನು ನಮೂದಿಸಿ:\nವಿದ್ಯುತ್ ರೇಟಿಂಗ್: 100W\nIP ರೇಟಿಂಗ್: IP65 ಅಥವಾ ಹೆಚ್ಚು',
    environment: 'ಆಪರೇಟಿಂಗ್ ಪರಿಸರ',
    envPlaceholder: 'ಉದಾ. ಹೊರಾಂಗಣ / ಕರಾವಳಿ / ಮಳೆಗಾಲದ ಪರಿಸ್ಥಿತಿಗಳು',
    industry: 'ಉದ್ಯಮ / ಕ್ಷೇತ್ರ',
    analyzeBtn: 'AI ಯೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಿ',
    chatPlaceholder: 'ನಿಮ್ಮ ಅವಶ್ಯಕತೆಯನ್ನು ವಿವರಿಸಿ ಅಥವಾ ಮಾನದಂಡಗಳ ಬಗ್ಗೆ ಕೇಳಿ...',
    chatGreeting: 'ನಮಸ್ಕಾರ! ನಾನು IS-SMART ಖರೀದಿ ಸಹಾಯಕ. ನಿಮ್ಮ ಅವಶ್ಯಕತೆಗಳಿಗೆ ಅನ್ವಯಿಸುವ ಭಾರತೀಯ ಮಾನದಂಡಗಳನ್ನು ಗುರುತಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತೇನೆ.',
    regionalNote: 'ಕನ್ನಡ, ಹಿಂದಿ, ತಮಿಳು, ತೆಲುಗು ಅಥವಾ ಮಲಯಾಳಂನಲ್ಲೂ ನಮೂದಿಸಬಹುದು.',
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    analyzeReq: 'ആവശ്യകത വിശകലനം ചെയ്യുക',
    tenderAnalyzer: 'ടെൻഡർ അനലൈസർ',
    specAssistant: 'സ്പെസിഫിക്കേഷൻ അസിസ്റ്റന്റ്',
    standardsExplorer: 'സ്റ്റാൻഡേർഡ് എക്സ്പ്ലോറർ',
    standardsGraph: 'സ്റ്റാൻഡേർഡ് ഗ്രാഫ്',
    gapAnalysis: 'ഗ്യാപ് അനാലിസിസ്',
    versionCheck: 'പതിപ്പും ഭേദഗതികളും',
    analysisHistory: 'വിശകലന ചരിത്രം',
    searchPlaceholder: 'മാനദണ്ഡങ്ങൾ, ഉൽപ്പന്നങ്ങൾ തിരയുക...',
    askIsSmart: 'IS-SMART-നോട് ചോദിക്കുക',
    systemStatus: 'സിസ്റ്റം നില',
    allOperational: 'എല്ലാ സിസ്റ്റങ്ങളും പ്രവർത്തിക്കുന്നു',
    aiStandardsIntel: 'AI അധിഷ്ഠിത ഇന്ത്യൻ സ്റ്റാൻഡേർഡ്സ് ഇന്റലിജൻസ്',
    heroTitlePart1: 'ശരിയായ ',
    indianStandards: 'ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ',
    heroTitlePart2: ' കണ്ടെത്തുക. മികച്ച ടെൻഡറുകൾ നിർമ്മിക്കുക.',
    heroSubtitle: 'ബാധകമായ ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ, സർട്ടിഫിക്കേഷനുകൾ, സ്പെസിഫിക്കേഷൻ ഇടവേളകൾ എന്നിവ കണ്ടെത്തുന്നതിന് AI സഹായം.',
    procurementPlaceholder: 'നിങ്ങളുടെ സംഭരണ ആവശ്യകത വിശദമായി വിവരിക്കുക... ഉദാഹരണത്തിന്: സർക്കാർ ആശുപത്രികൾക്കായി 500 സ്റ്റെയിൻലെസ്സ് സ്റ്റീൽ വാട്ടർ ടാങ്കുകൾ വാങ്ങുക',
    uploadTenderDoc: 'ടെൻഡർ രേഖ അപ്‌ലോഡ് ചെയ്യുക',
    analyzeRequirement: 'ആവശ്യകത വിശകലനം ചെയ്യുക',
    standardsIndexed: 'ഇൻഡക്സ് ചെയ്ത മാനദണ്ഡങ്ങൾ',
    acrossAllSectors: 'എല്ലാ മേഖലകളിലും',
    relationshipsMapped: 'മാപ്പ് ചെയ്ത ബന്ധങ്ങൾ',
    standardsInterconnections: 'മാനദണ്ഡങ്ങളുടെ പരസ്പര ബന്ധങ്ങൾ',
    tendersAnalyzed: 'വിശകലനം ചെയ്ത ടെൻഡറുകൾ',
    thisMonth: 'ഈ മാസം',
    issuesDetected: 'കണ്ടെത്തിയ പ്രശ്നങ്ങൾ',
    potentialSpecGaps: 'സാധ്യമായ സ്പെസിഫിക്കേഷൻ ഇടവേളകൾ',
    aiAnalysisPipeline: 'AI വിശകലന പൈപ്പ്‌ലൈൻ',
    viewFullPipeline: 'മുഴുവൻ പൈപ്പ്‌ലൈൻ കാണുക',
    stepInputRequirement: 'ആവശ്യകത ഇൻപുട്ട്',
    stepAiAnalysis: 'AI വിശകലനം',
    stepUnderstanding: 'ധാരണ',
    stepProductId: 'ഉൽപ്പന്ന ഐഡി',
    stepIdentification: 'തിരിച്ചറിയൽ',
    stepReqExtraction: 'ആവശ്യകത വേർതിരിച്ചെടുക്കൽ',
    stepKeyParameters: 'പ്രധാന പാരാമീറ്ററുകൾ',
    stepStandardsMatching: 'മാനദണ്ഡ പൊരുത്തം',
    stepAiMatching: 'AI പൊരുത്തം',
    stepRelationships: 'ബന്ധങ്ങൾ',
    stepMapping: 'മാപ്പിംഗ്',
    stepVersionCheck: 'പതിപ്പ് പരിശോധന',
    stepLatestVersions: 'ഏറ്റവും പുതിയ പതിപ്പുകൾ',
    stepGapAnalysis: 'ഗ്യാപ് വിശകലനം',
    stepIssueDetection: 'പ്രശ്ന കണ്ടെത്തൽ',
    stepCertifications: 'സർട്ടിഫിക്കേഷനുകൾ',
    stepValidations: 'സ്ഥിരീകരണം',
    stepSpecGeneration: 'സ്പെസിഫിക്കേഷൻ നിർമ്മാണം',
    stepOutput: 'ഔട്ട്പുട്ട്',
    recentAnalyses: 'സമീപകാല വിശകലനങ്ങൾ',
    viewAll: 'എല്ലാം കാണുക',
    topStandardsByUsage: 'ഉപയോഗത്തിൽ മുന്നിലുള്ള മാനദണ്ഡങ്ങൾ',
    explore: 'തിരയുക',
    issueSummary: 'പ്രശ്ന സംഗ്രഹം',
    completed: 'പൂർത്തിയായി',
    totalIssues: 'ആകെ പ്രശ്നങ്ങൾ',
    missing: 'ഇല്ലാത്തവ',
    outdated: 'പഴയത്',
    ambiguous: 'അവ്യക്തം',
    certGaps: 'സർട്ടിഫിക്കറ്റ് ഇടവേളകൾ',
    product: 'ഉൽപ്പന്നം / സേവനം',
    productPlaceholder: 'ഉദാ. LED തെരുവ് വിളക്ക്, വ്യാവസായിക ജലപമ്പ്',
    purpose: 'ഉദ്ദേശ്യം / ആപ്ലിക്കേഷൻ',
    purposePlaceholder: 'ഉദാ. ദേശീയ പാതാ അടിസ്ഥാന സൗകര്യത്തിനുള്ള റോഡ് ലൈറ്റിംഗ്',
    techReq: 'സാങ്കേതിക ആവശ്യകതകൾ',
    techReqPlaceholder: 'സാങ്കേതിക ആവശ്യകതകൾ നൽകുക:\nശക്തി റേറ്റിംഗ്: 100W\nIP റേറ്റിംഗ്: IP65 അല്ലെങ്കിൽ അതിൽ കൂടുതൽ',
    environment: 'പ്രവർത്തന പരിതസ്ഥിതി',
    envPlaceholder: 'ഉദാ. ഔട്ട്ഡോർ / തീരദേശം / മൺസൂൺ അവസ്ഥകൾ',
    industry: 'വ്യവസായം / മേഖല',
    analyzeBtn: 'AI ഉപയോഗിച്ച് വിശകലനം ചെയ്യുക',
    chatPlaceholder: 'നിങ്ങളുടെ ആവശ്യകത വിവരിക്കുക അല്ലെങ്കിൽ മാനദണ്ഡങ്ങളെ കുറിച്ച് ചോദിക്കുക...',
    chatGreeting: 'നമസ്കാരം! ഞാൻ IS-SMART സംഭരണ സഹായിയാണ്. നിങ്ങളുടെ ആവശ്യകതകൾക്ക് ബാധകമായ ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ കണ്ടെത്താൻ ഞാൻ സഹായിക്കാം.',
    regionalNote: 'മലയാളം, ഹിന്ദി, തമിഴ്, തെലുഗു അല്ലെങ്കിൽ കന്നഡയിലും ടൈപ്പ് ചെയ്യാം.',
  },
};

// ── Context ───────────────────────────────────────────────────
interface LanguageContextValue {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
});

const STORAGE_KEY = 'is-smart-language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('en');

  // Load from localStorage on mount
  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY) as LangCode | null;
      if (stored && LANGUAGES.find((l) => l.code === stored)) {
        setLangState(stored);
        document.documentElement.lang = stored;
      } else {
        document.documentElement.lang = 'en';
      }
    } catch {
      document.documentElement.lang = 'en';
    }
  }, []);

  function setLang(code: LangCode) {
    setLangState(code);
    document.documentElement.lang = code;
    try { localStorage.setItem(STORAGE_KEY, code); } catch {}
  }

  function t(key: string): string {
    return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
