'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LangCode = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'ml';

export interface LangMeta {
  code: LangCode;
  label: string;
  name: string;
  flag: string;
}

export const LANGUAGES: LangMeta[] = [
  { code: 'en', label: 'EN', name: 'English', flag: '🇮🇳' },
  { code: 'hi', label: 'हि', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', label: 'த', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'తె', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', label: 'ಕ', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', label: 'മ', name: 'മലയാളം', flag: '🇮🇳' },
];

// ── Comprehensive Global Translations Dictionary for all 6 languages ───────────────
export const TRANSLATIONS: Record<LangCode, Record<string, string>> = {
  en: {
    // Navigation & App Shell
    dashboard: 'Dashboard',
    analyzeReq: 'Analyze Requirement',
    tenderAnalyzer: 'Tender Analyzer',
    specAssistant: 'Spec Assistant',
    standardsExplorer: 'Standards Explorer',
    standardsGraph: 'Standards Graph',
    gapAnalysis: 'Gap Analysis',
    versionCheck: 'Version & Amendments',
    certification: 'Certification',
    analysisHistory: 'Analysis History',
    howItWorks: 'How It Works',
    about: 'About',
    searchPlaceholder: 'Search standards, products, tenders...',
    askIsSmart: 'Ask IS-SMART',
    systemStatus: 'SYSTEM STATUS',
    allOperational: 'All Systems Operational',

    // Hero & Home
    aiStandardsIntel: 'AI-Powered Standards Intelligence',
    heroTitlePart1: 'FIND THE RIGHT ',
    indianStandards: 'INDIAN STANDARDS',
    heroTitlePart2: '. BUILD BETTER TENDERS.',
    heroSubtitle: 'AI-assisted Indian Standards intelligence for procurement, tender specification, compliance review and technical requirement analysis.',
    startAnalysis: 'Start Analysis',
    exploreStandards: 'Explore Standards',
    procurementPlaceholder: 'Describe your procurement requirement in detail... Example: Procure 500 stainless steel water storage tanks of 750 litre capacity for government hospitals',
    uploadTenderDoc: 'Upload Tender Document',

    // Project Input Workspace & Common Actions
    projectWorkspace: 'Project Input Workspace',
    noActiveProject: 'No Active Project',
    createProject: 'Create Project',
    createNewProject: 'Create New User Project',
    editProject: 'Edit Active Project',
    projectName: 'Project Name',
    tenderTextLabel: 'Tender / Technical Requirement Text',
    pasteTenderText: 'Paste Tender Text',
    loadPresetExample: '⚡ Load Preset Example...',
    saveAndActivate: 'Save & Activate Project',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    upload: 'Upload',
    search: 'Search',
    loading: 'Loading...',
    processing: 'Processing...',
    confirm: 'Confirm Requirements',
    findStandards: 'Find Standards',
    runAnalysis: 'Run Analysis',
    viewDetails: 'View Details',
    viewSource: 'View Source',
    copyEvidence: 'Copy Evidence',
    whyThisStandard: 'Why This Standard?',
    viewEvidence: 'View Evidence',
    relatedStandards: 'Related Standards',

    // Metric Cards & Pipeline
    standardsIndexed: 'Standards Indexed',
    acrossAllSectors: 'Across all sectors',
    relationshipsMapped: 'Relationships Mapped',
    standardsInterconnections: 'Standards interconnections',
    tendersAnalyzed: 'Tenders Analyzed',
    thisMonth: 'This month',
    issuesDetected: 'Issues Detected',
    potentialSpecGaps: 'Potential spec gaps',
    aiAnalysisPipeline: 'AI Analysis Pipeline',
    recentAnalyses: 'Recent Analyses',
    topStandardsByUsage: 'Top Standards by Usage',
    issueSummary: 'Issue Summary',
    totalIssues: 'TOTAL ISSUES',

    // Status Badges & Table Labels
    match: '✓ MATCH',
    missing: '⚠ MISSING',
    ambiguous: '⚠ AMBIGUOUS',
    outdated: '❌ OUTDATED',
    needsReview: 'ℹ REVIEW',
    completed: 'Completed',
    current: 'Current',
    amended: 'Amended',
    superseded: 'Superseded',
    withdrawn: 'Withdrawn',
    underRevision: 'Under Revision',
    draft: 'Draft',
    confirmedMatch: '✓ Confirmed Match',
    potentialMatch: 'Potential Match',

    // Requirement & Analysis Headers
    extractedRequirements: 'EXTRACTED REQUIREMENTS',
    product: 'Product Name',
    quantity: 'Quantity',
    capacity: 'Capacity',
    material: 'Material',
    application: 'Application',
    otherRequirements: 'Other Requirements',
    confidence: 'Confidence',
    relevance: 'Relevance',
    evidenceAndTraceability: 'EVIDENCE & TRACEABILITY',
    parameter: 'Parameter',
    tenderValue: 'Tender Value',
    standardRequirement: 'Standard Requirement',
    status: 'Status',

    // Disclaimer
    responsibleAiNotice: 'Trust & Responsible AI Notice: IS-SMART provides AI-assisted standards recommendations based on indexed information. Always verify the latest official BIS publication, amendment, notification and applicable certification requirements before using the output in a procurement decision.',
  },

  hi: {
    dashboard: 'डैशबोर्ड',
    analyzeReq: 'आवश्यकता का विश्लेषण करें',
    tenderAnalyzer: 'निविदा विश्लेषक',
    specAssistant: 'विनिर्देश सहायक',
    standardsExplorer: 'मानक एक्सप्लोरर',
    standardsGraph: 'मानक ग्राफ',
    gapAnalysis: 'अंतर विश्लेषण',
    versionCheck: 'संस्करण और संशोधन',
    certification: 'प्रमाणन',
    analysisHistory: 'विश्लेषण इतिहास',
    howItWorks: 'यह कैसे काम करता है',
    about: 'हमारे बारे में',
    searchPlaceholder: 'मानक, उत्पाद, निविदाएं खोजें...',
    askIsSmart: 'IS-SMART से पूछें',
    systemStatus: 'सिस्टम स्थिति',
    allOperational: 'सभी प्रणालियां चालू हैं',

    aiStandardsIntel: 'एआई-संचालित भारतीय मानक इंटेलिजेंस',
    heroTitlePart1: 'सही ',
    indianStandards: 'भारतीय मानक',
    heroTitlePart2: ' खोजें। बेहतर निविदाएं बनाएं।',
    heroSubtitle: 'खरीद, निविदा विनिर्देश, अनुपालन समीक्षा और तकनीकी आवश्यकता विश्लेषण के लिए एआई-सहायता प्राप्त भारतीय मानक इंटेलिजेंस।',
    startAnalysis: 'विश्लेषण शुरू करें',
    exploreStandards: 'मानकों की खोज करें',
    procurementPlaceholder: 'अपनी खरीद आवश्यकता का विस्तार से वर्णन करें... उदाहरण: सरकारी अस्पतालों के लिए 750 लीटर क्षमता के 500 स्टेनलेस स्टील पानी के टैंक खरीदें',
    uploadTenderDoc: 'निविदा दस्तावेज अपलोड करें',

    projectWorkspace: 'परियोजना इनपुट कार्यक्षेत्र',
    noActiveProject: 'कोई सक्रिय परियोजना नहीं',
    createProject: 'परियोजना बनाएं',
    createNewProject: 'नई उपयोगकर्ता परियोजना बनाएं',
    editProject: 'सक्रिय परियोजना संपादित करें',
    projectName: 'परियोजना का नाम',
    tenderTextLabel: 'निविदा / तकनीकी आवश्यकता पाठ',
    pasteTenderText: 'निविदा पाठ चिपकाएं',
    loadPresetExample: '⚡ पूर्व निर्धारित उदाहरण लोड करें...',
    saveAndActivate: 'सहेजें और परियोजना सक्रिय करें',
    saveChanges: 'परिवर्तन सहेजें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    upload: 'अपलोड करें',
    search: 'खोजें',
    loading: 'लोड हो रहा है...',
    processing: 'प्रसंस्करण चल रहा है...',
    confirm: 'आवश्यकताओं की पुष्टि करें',
    findStandards: 'मानक खोजें',
    runAnalysis: 'विश्लेषण चलाएं',
    viewDetails: 'विवरण देखें',
    viewSource: 'स्रोत देखें',
    copyEvidence: 'साक्ष्य कॉपी करें',
    whyThisStandard: 'यह मानक क्यों?',
    viewEvidence: 'साक्ष्य देखें',
    relatedStandards: 'संबंधित मानक',

    standardsIndexed: 'अनुक्रमित मानक',
    acrossAllSectors: 'सभी क्षेत्रों में',
    relationshipsMapped: 'मैप किए गए संबंध',
    standardsInterconnections: 'मानक अंतर्संबंध',
    tendersAnalyzed: 'विश्लेषित निविदाएं',
    thisMonth: 'इस महीने',
    issuesDetected: 'खोजे गए मुद्दे',
    potentialSpecGaps: 'संभावित विनिर्देश अंतराल',
    aiAnalysisPipeline: 'एआई विश्लेषण पाइपलाइन',
    recentAnalyses: 'हाल के विश्लेषण',
    topStandardsByUsage: 'उपयोग के अनुसार शीर्ष मानक',
    issueSummary: 'मुद्दा सारांश',
    totalIssues: 'कुल मुद्दे',

    match: '✓ मिलान',
    missing: '⚠ अनुपस्थित',
    ambiguous: '⚠ अस्पष्ट',
    outdated: '❌ पुराना',
    needsReview: 'ℹ समीक्षा की आवश्यकता',
    completed: 'पूरा हुआ',
    current: 'वर्तमान',
    amended: 'संशोधित',
    superseded: 'अतिक्रमित',
    withdrawn: 'वापस लिया गया',
    underRevision: 'संशोधनाधीन',
    draft: 'प्रारूप',
    confirmedMatch: '✓ पुष्ट मिलान',
    potentialMatch: 'संभावित मिलान',

    extractedRequirements: 'निष्कर्षित आवश्यकताएं',
    product: 'उत्पाद का नाम',
    quantity: 'मात्रा',
    capacity: 'क्षमता',
    material: 'सामग्री',
    application: 'अनुप्रयोग',
    otherRequirements: 'अन्य आवश्यकताएं',
    confidence: 'विश्वसनीयता',
    relevance: 'प्रासंगिकता',
    evidenceAndTraceability: 'साक्ष्य और पता लगाने की क्षमता',
    parameter: 'पैरामीटर',
    tenderValue: 'निविदा मूल्य',
    standardRequirement: 'मानक आवश्यकता',
    status: 'स्थिति',

    responsibleAiNotice: 'विश्वसनीय और जिम्मेदार एआई नोटिस: IS-SMART अनुक्रमित जानकारी के आधार पर एआई-सहायता प्राप्त मानक सिफारिशें प्रदान करता है। खरीद निर्णय में आउटपुट का उपयोग करने से पहले हमेशा नवीनतम आधिकारिक बीआईएस प्रकाशन, संशोधन और लागू प्रमाणन आवश्यकताओं को सत्यापित करें।',
  },

  ta: {
    dashboard: 'டாஷ்போர்டு',
    analyzeReq: 'தேவையை ஆராயுங்கள்',
    tenderAnalyzer: 'டெண்டர் ஆய்வாளர்',
    specAssistant: 'குறிப்பீட்டு உதவியாளர்',
    standardsExplorer: 'தரநிலைகள் உலாவி',
    standardsGraph: 'தரநிலைகள் வரைபடம்',
    gapAnalysis: 'இடைவெளி பகுப்பாய்வு',
    versionCheck: 'பதிப்பு மற்றும் திருத்தங்கள்',
    certification: 'சான்றிதழ்',
    analysisHistory: 'பகுப்பாய்வு வரலாறு',
    howItWorks: 'இது எவ்வாறு இயங்குகிறது',
    about: 'எங்களைப் பற்றி',
    searchPlaceholder: 'தரநிலைகள், தயாரிப்புகளைத் தேடுங்கள்...',
    askIsSmart: 'IS-SMART இடம் கேளுங்கள்',
    systemStatus: 'அமைப்பு நிலை',
    allOperational: 'அனைத்து அமைப்புகளும் செயல்படுகின்றன',

    aiStandardsIntel: 'AI-இயங்கும் இந்திய தரநிலைகள் நுண்ணறிவு',
    heroTitlePart1: 'சரியான ',
    indianStandards: 'இந்திய தரநிலைகளை',
    heroTitlePart2: ' கண்டறியவும். சிறந்த டெண்டர்களை உருவாக்குங்கள்.',
    heroSubtitle: 'கொள்முதல், டெண்டர் விவரக்குறிப்பு, இணக்க மதிப்பாய்வு மற்றும் தொழில்நுட்ப தேவை பகுப்பாய்வுக்கான AI-உதவி இந்திய தரநிலைகள் நுண்ணறிவு.',
    startAnalysis: 'பகுப்பாய்வைத் தொடங்குங்கள்',
    exploreStandards: 'தரநிலைகளை ஆராயுங்கள்',
    procurementPlaceholder: 'உங்கள் கொள்முதல் தேவையை விரிவாக விவரிக்கவும்... எ.கா: அரசு மருத்துவமனைகளுக்கு 750 லிட்டர் கொள்ளளவு கொண்ட 500 துருப்பிடிக்காத எஃகு தண்ணீர் தொட்டிகளை வாங்கவும்',
    uploadTenderDoc: 'டெண்டர் ஆவணத்தைப் பதிவேற்றவும்',

    projectWorkspace: 'திட்ட உள்ளீட்டு பணியிடம்',
    noActiveProject: 'செயலில் உள்ள திட்டம் இல்லை',
    createProject: 'திட்டத்தை உருவாக்குங்கள்',
    createNewProject: 'புதிய பயனர் திட்டத்தை உருவாக்குங்கள்',
    editProject: 'செயலில் உள்ள திட்டத்தைத் திருத்துங்கள்',
    projectName: 'திட்டத்தின் பெயர்',
    tenderTextLabel: 'டெண்டர் / தொழில்நுட்ப தேவை உரை',
    pasteTenderText: 'டெண்டர் உரையை ஒட்டவும்',
    loadPresetExample: '⚡ முன்னமைக்கப்பட்ட உதாரணத்தை ஏற்றவும்...',
    saveAndActivate: 'சேமித்து திட்டத்தை செயல்படுத்துங்கள்',
    saveChanges: 'மாற்றங்களைச் சேமிக்கவும்',
    cancel: 'ரத்துசெய்',
    save: 'சேமி',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    upload: 'பதிவேற்று',
    search: 'தேடு',
    loading: 'ஏற்றுகிறது...',
    processing: 'செயலாக்கப்படுகிறது...',
    confirm: 'தேவைகளை உறுதிப்படுத்தவும்',
    findStandards: 'தரநிலைகளைக் கண்டறியவும்',
    runAnalysis: 'பகுப்பாய்வை இயக்கவும்',
    viewDetails: 'விவரங்களைக் காண்க',
    viewSource: 'மூலத்தைக் காண்க',
    copyEvidence: 'சான்றைப் நகலெடு',
    whyThisStandard: 'ஏன் இந்த தரநிலை?',
    viewEvidence: 'சான்றைக் காண்க',
    relatedStandards: 'தொடர்புடைய தரநிலைகள்',

    standardsIndexed: 'அடைவடைக்கப்பட்ட தரநிலைகள்',
    acrossAllSectors: 'அனைத்து துறைகளிலும்',
    relationshipsMapped: 'வரைபடமாக்கப்பட்ட உறவுகள்',
    standardsInterconnections: 'தரநிலைகள் இணைப்பு',
    tendersAnalyzed: 'பகுப்பாய்வு செய்யப்பட்ட டெண்டர்கள்',
    thisMonth: 'இந்த மாதம்',
    issuesDetected: 'கண்டறியப்பட்ட சிக்கல்கள்',
    potentialSpecGaps: 'சாத்தியமான விவரக்குறிப்பு இடைவெளிகள்',
    aiAnalysisPipeline: 'AI பகுப்பாய்வு பைப்லைன்',
    recentAnalyses: 'சமீபத்திய பகுப்பாய்வுகள்',
    topStandardsByUsage: 'பயன்பாட்டின் அடிப்படையில் சிறந்த தரநிலைகள்',
    issueSummary: 'சிக்கல் சுருக்கம்',
    totalIssues: 'மொத்த சிக்கல்கள்',

    match: '✓ பொருத்தம்',
    missing: '⚠ காணவில்லை',
    ambiguous: '⚠ தெளிவற்றது',
    outdated: '❌ பழையது',
    needsReview: 'ℹ மதிப்பாய்வு தேவை',
    completed: 'நிறைவடைந்தது',
    current: 'தற்போதைய',
    amended: 'திருத்தப்பட்டது',
    superseded: 'மாற்றப்பட்டது',
    withdrawn: 'திரும்பப் பெறப்பட்டது',
    underRevision: 'மறுபரிசீலனையில்',
    draft: 'வரைவு',
    confirmedMatch: '✓ உறுதிப்படுத்தப்பட்ட பொருத்தம்',
    potentialMatch: 'சாத்தியமான பொருத்தம்',

    extractedRequirements: 'பிரித்தெடுக்கப்பட்ட தேவைகள்',
    product: 'தயாரிப்பு பெயர்',
    quantity: 'அளவு',
    capacity: 'கொள்ளளவு',
    material: 'பொருள்',
    application: 'பயன்பாடு',
    otherRequirements: 'இதர தேவைகள்',
    confidence: 'நம்பகத்தன்மை',
    relevance: 'பொருத்தம்',
    evidenceAndTraceability: 'சான்று மற்றும் தடமறியும் தன்மை',
    parameter: 'அளவுரு',
    tenderValue: 'டெண்டர் மதிப்பு',
    standardRequirement: 'தரநிலை தேவை',
    status: 'நிலை',

    responsibleAiNotice: 'நம்பகமான AI அறிவிப்பு: IS-SMART அட்டவணைப்படுத்தப்பட்ட தகவல்களின் அடிப்படையில் AI பரிந்துரைகளை வழங்குகிறது. கொள்முதல் முடிவில் பயன்படுத்துவதற்கு முன் எப்போதும் சமீபத்திய உத்தியோகபூர்வ BIS வெளியீடு மற்றும் சான்றிதழ் தேவைகளை சரிபார்க்கவும்.',
  },

  te: {
    dashboard: 'డాష్‌బోర్డ్',
    analyzeReq: 'అవసరాన్ని విశ్లేషించండి',
    tenderAnalyzer: 'టెండర్ అనలైజర్',
    specAssistant: 'స్పెసిఫికేషన్ అసిస్టెంట్',
    standardsExplorer: 'స్టాండర్డ్స్ ఎక్స్‌ప్లోరర్',
    standardsGraph: 'స్టాండర్డ్స్ గ్రాఫ్',
    gapAnalysis: 'గ్యాప్ అనాలిసిస్',
    versionCheck: 'వెర్షన్ & సవరణలు',
    certification: 'సర్టిఫికేషన్',
    analysisHistory: 'విశ్లేషణ చరిత్ర',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    about: 'మా గురించి',
    searchPlaceholder: 'ప్రమాణాలు, ఉత్పత్తులను శోధించండి...',
    askIsSmart: 'IS-SMART ని అడగండి',
    systemStatus: 'సిస్టమ్ స్థితి',
    allOperational: 'అన్ని సిస్టమ్‌లు నడుస్తున్నాయి',

    aiStandardsIntel: 'AI-ఆధారిత భారతీయ ప్రమాణాల ఇంటెలిజెన్స్',
    heroTitlePart1: 'సరైన ',
    indianStandards: 'భారతీయ ప్రమాణాలను',
    heroTitlePart2: ' కనుగొనండి. మెరుగైన టెండర్లను నిర్మించండి.',
    heroSubtitle: 'వర్తించే భారతీయ ప్రమాణాలు, ధృవీకరణలు మరియు స్పెసిఫికేషన్ లోపాలను గుర్తించడానికి AI సహాయం.',
    startAnalysis: 'విశ్లేషణ ప్రారంభించండి',
    exploreStandards: 'ప్రమాణాలను అన్వేషించండి',
    procurementPlaceholder: 'మీ సేకరణ అవసరాన్ని వివరంగా వివరించండి... ఉదాహరణ: ప్రభుత్వ ఆసుపత్రుల కోసం 750 లీటర్ల సామర్థ్యం గల 500 స్టెయిన్‌లెస్ స్టీల్ నీటి నిల్వ ట్యాంకులను కొనుగోలు చేయండి',
    uploadTenderDoc: 'టెండర్ పత్రాన్ని అప్‌లోడ్ చేయండి',

    projectWorkspace: 'ప్రాజెక్ట్ ఇన్‌పుట్ వర్క్‌స్పేస్',
    noActiveProject: 'యాక్టివ్ ప్రాజెక్ట్ లేదు',
    createProject: 'ప్రాజెక్ట్ సృష్టించండి',
    createNewProject: 'కొత్త ప్రాజెక్ట్ సృష్టించండి',
    editProject: 'యాక్టివ్ ప్రాజెక్ట్ ఎడిట్ చేయండి',
    projectName: 'ప్రాజెక్ట్ పేరు',
    tenderTextLabel: 'టెండర్ / సాంకేతిక అవసరాల టెక్స్ట్',
    pasteTenderText: 'టెండర్ టెక్స్ట్ పేస్ట్ చేయండి',
    loadPresetExample: '⚡ ముందుగా నిర్వచించిన ఉదాహరణను లోడ్ చేయండి...',
    saveAndActivate: 'సేవ్ చేసి యాక్టివేట్ చేయండి',
    saveChanges: 'మార్పులను సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    save: 'సేవ్ చేయండి',
    edit: 'ఎడిట్ చేయండి',
    delete: 'తొలగించండి',
    upload: 'అప్‌లోడ్ చేయండి',
    search: 'శోధించండి',
    loading: 'లోడ్ అవుతోంది...',
    processing: 'ప్రాసెస్ అవుతోంది...',
    confirm: 'అవసరాలను ధృవీకరించండి',
    findStandards: 'ప్రమాణాలను కనుగొనండి',
    runAnalysis: 'విశ్లేషణ చేయండి',
    viewDetails: 'వివరాలు చూడండి',
    viewSource: 'మూలాన్ని చూడండి',
    copyEvidence: 'సాక్ష్యాధారాలు కాపీ చేయండి',
    whyThisStandard: 'ఈ ప్రమాణం ఎందుకు?',
    viewEvidence: 'సాక్ష్యాధారాలు చూడండి',
    relatedStandards: 'సంబంధిత ప్రమాణాలు',

    standardsIndexed: 'ఇండెక్స్ చేసిన ప్రమాణాలు',
    acrossAllSectors: 'అన్ని రంగాలలో',
    relationshipsMapped: 'మ్యాప్ చేసిన సంబంధాలు',
    standardsInterconnections: 'ప్రమాణాల అనుసంధానాలు',
    tendersAnalyzed: 'విశ్లేషించిన టెండర్లు',
    thisMonth: 'ఈ నెలలో',
    issuesDetected: 'గుర్తించిన సమస్యలు',
    potentialSpecGaps: 'సాధ్యమైన స్పెసిఫికేషన్ లోపాలు',
    aiAnalysisPipeline: 'AI విశ్లేషణ పైప్‌లైన్',
    recentAnalyses: 'ఇటీవలి విశ్లేషణలు',
    topStandardsByUsage: 'ఉపయోగం ప్రకారం అగ్ర ప్రమాణాలు',
    issueSummary: 'సమస్యల సారాంశం',
    totalIssues: 'మొత్తం సమస్యలు',

    match: '✓ సరిపోలింది',
    missing: '⚠ లేదు',
    ambiguous: '⚠ అస్పష్టం',
    outdated: '❌ పాతది',
    needsReview: 'ℹ సమీక్ష అవసరం',
    completed: 'పూర్తయింది',
    current: 'ప్రస్తుతం',
    amended: 'సవరించబడింది',
    superseded: 'భర్తీ చేయబడింది',
    withdrawn: 'ఉపసంహరించబడింది',
    underRevision: 'సమీక్షలో ఉంది',
    draft: 'ముసాయిదా',
    confirmedMatch: '✓ ధృవీకరించబడిన సరిపోలిక',
    potentialMatch: 'సాధ్యమైన సరిపోలిక',

    extractedRequirements: 'సేకరించిన అవసరాలు',
    product: 'ఉత్పత్తి పేరు',
    quantity: 'పరిమాణం',
    capacity: 'సామర్థ్యం',
    material: 'పదార్థం',
    application: 'అప్లికేషన్',
    otherRequirements: 'ఇతర అవసరాలు',
    confidence: 'నమ్మకం',
    relevance: 'ప్రాముఖ్యత',
    evidenceAndTraceability: 'సాక్ష్యాధారాలు & పరిశీలన',
    parameter: 'పారామీటర్',
    tenderValue: 'టెండర్ విలువ',
    standardRequirement: 'ప్రమాణాల అవసరం',
    status: 'స్థితి',

    responsibleAiNotice: 'బాధ్యతాయుతమైన AI నోటీసు: IS-SMART ఇండెక్స్ చేసిన సమాచారం ఆధారంగా AI సిఫార్సులను అందిస్తుంది. సేకరణ నిర్ణయంలో ఉపయోగించే ముందు అధికారిక BIS ప్రచురణలను ధృవీకరించండి.',
  },

  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    analyzeReq: 'ಅವಶ್ಯಕತೆ ವಿಶ್ಲೇಷಿಸಿ',
    tenderAnalyzer: 'ಟೆಂಡರ್ ವಿಶ್ಲೇಷಕ',
    specAssistant: 'ಸ್ಪೆಸಿಫಿಕೇಶನ್ ಸಹಾಯಕ',
    standardsExplorer: 'ಮಾನದಂಡಗಳ ಎಕ್ಸ್‌ಪ್ಲೋರರ್',
    standardsGraph: 'ಮಾನದಂಡಗಳ ಗ್ರಾಫ್',
    gapAnalysis: 'ಗ್ಯಾಪ್ ವಿಶ್ಲೇಷಣೆ',
    versionCheck: 'ಆವೃತ್ತಿ ಮತ್ತು ತಿದ್ದುಪಡಿಗಳು',
    certification: 'ಪ್ರಮಾಣೀಕರಣ',
    analysisHistory: 'ವಿಶ್ಲೇಷಣೆ ಇತಿಹಾಸ',
    howItWorks: 'ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    searchPlaceholder: 'ಮಾನದಂಡಗಳು, ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...',
    askIsSmart: 'IS-SMART ಕೇಳಿ',
    systemStatus: 'ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ',
    allOperational: 'ಎಲ್ಲಾ ಸಿಸ್ಟಮ್‌ಗಳು ಕಾರ್ಯಾಚರಣೆಯಲ್ಲಿವೆ',

    aiStandardsIntel: 'AI-ಚಾಲಿತ ಭಾರತೀಯ ಮಾನದಂಡಗಳ ಇಂಟೆಲಿಜೆನ್ಸ್',
    heroTitlePart1: 'ಸರಿಯಾದ ',
    indianStandards: 'ಭಾರತೀಯ ಮಾನದಂಡಗಳನ್ನು',
    heroTitlePart2: ' ಕಂಡುಕೊಳ್ಳಿ. ಉತ್ತಮ ಟೆಂಡರ್‌ಗಳನ್ನು ನಿರ್ಮಿಸಿ.',
    heroSubtitle: 'ಅನ್ವಯವಾಗುವ ಭಾರತೀಯ ಮಾನದಂಡಗಳು, ಪ್ರಮಾಣಪತ್ರಗಳು ಮತ್ತು ವಿವರಣೆ ಕೊರತೆಗಳನ್ನು ಗುರುತಿಸಲು AI ನೆರವು.',
    startAnalysis: 'ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ',
    exploreStandards: 'ಮಾನದಂಡಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    procurementPlaceholder: 'ನಿಮ್ಮ ಖರೀದಿ ಅವಶ್ಯಕತೆಯನ್ನು ವಿವರವಾಗಿ ವಿವರಿಸಿ... ಉದಾಹರಣೆಗೆ: ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆಗಳಿಗೆ 750 ಲೀಟರ್ ಸಾಮರ್ಥ್ಯದ 500 ಸ್ಟೇನ್‌ಲೆಸ್ ಸ್ಟೀಲ್ ನೀರಿನ ಟ್ಯಾಂಕ್‌ಗಳನ್ನು ಖರೀದಿಸಿ',
    uploadTenderDoc: 'ಟೆಂಡರ್ ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',

    projectWorkspace: 'ಯೋಜನೆ ಇನ್‌ಪುಟ್ ವರ್ಕ್‌ಸ್ಪೇಸ್',
    noActiveProject: 'ಯಾವುದೇ ಸಕ್ರಿಯ ಯೋಜನೆ ಇಲ್ಲ',
    createProject: 'ಯೋಜನೆ ರಚಿಸಿ',
    createNewProject: 'ಹೊಸ ಬಳಕೆದಾರ ಯೋಜನೆ ರಚಿಸಿ',
    editProject: 'ಸಕ್ರಿಯ ಯೋಜನೆ ಸಂಪಾದಿಸಿ',
    projectName: 'ಯೋಜನೆಯ ಹೆಸರು',
    tenderTextLabel: 'ಟೆಂಡರ್ / ತಾಂತ್ರಿಕ ಅವಶ್ಯಕತೆ ಪಠ್ಯ',
    pasteTenderText: 'ಟೆಂಡರ್ ಪಠ್ಯವನ್ನು ಅಂಟಿಸಿ',
    loadPresetExample: '⚡ ಪೂರ್ವನಿರ್ಧರಿತ ಉದಾಹರಣೆ ಲೋಡ್ ಮಾಡಿ...',
    saveAndActivate: 'ಉಳಿಸಿ ಮತ್ತು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಗೊಳಿಸಿ',
    save: 'ಉಳಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    delete: 'ಳಿಸಿ',
    upload: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    search: 'ಹುಡುಕಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    processing: 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    confirm: 'ಅವಶ್ಯಕತೆಗಳನ್ನು ದೃಢೀಕರಿಸಿ',
    findStandards: 'ಮಾನದಂಡಗಳನ್ನು ಹುಡುಕಿ',
    runAnalysis: 'ವಿಶ್ಲೇಷಣೆ ಚಲಾಯಿಸಿ',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    viewSource: 'ಮೂಲವನ್ನು ವೀಕ್ಷಿಸಿ',
    copyEvidence: 'ಸಾಕ್ಷ್ಯವನ್ನು ನಕಲಿಸಿ',
    whyThisStandard: 'ಈ ಮಾನದಂಡ ಏಕೆ?',
    viewEvidence: 'ಸಾಕ್ಷ್ಯ ವೀಕ್ಷಿಸಿ',
    relatedStandards: 'ಸಂಬಂಧಿತ ಮಾನದಂಡಗಳು',

    standardsIndexed: 'ಸೂಚ್ಯಂಕಿತ ಮಾನದಂಡಗಳು',
    acrossAllSectors: 'ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ',
    relationshipsMapped: 'ಮ್ಯಾಪ್ ಮಾಡಿದ ಸಂಬಂಧಗಳು',
    standardsInterconnections: 'ಮಾನದಂಡಗಳ ಸಂಪರ್ಕಗಳು',
    tendersAnalyzed: 'ವಿಶ್ಲೇಷಿಸಿದ ಟೆಂಡರ್‌ಗಳು',
    thisMonth: 'ಈ ತಿಂಗಳು',
    issuesDetected: 'ಗುರುತಿಸಲಾದ ಸಮಸ್ಯೆಗಳು',
    potentialSpecGaps: 'ಸಂಭಾವ್ಯ ವಿವರಣೆ ಕೊರತೆಗಳು',
    aiAnalysisPipeline: 'AI ವಿಶ್ಲೇಷಣೆ ಪೈಪ್‌ಲೈನ್',
    recentAnalyses: 'ಇತ್ತೀಚಿನ ವಿಶ್ಲೇಷಣೆಗಳು',
    topStandardsByUsage: 'ಬಳಕೆಯ ಆಧಾರದ ಮೇಲೆ ಪ್ರಮುಖ ಮಾನದಂಡಗಳು',
    issueSummary: 'ಸಮಸ್ಯೆಗಳ ಸಾರಾಂಶ',
    totalIssues: 'ಒಟ್ಟು ಸಮಸ್ಯೆಗಳು',

    match: '✓ ಹೋಲಿಕೆಯಾಗಿದೆ',
    missing: '⚠ ಕಾಣೆಯಾಗಿದೆ',
    ambiguous: '⚠ ಅಸ್ಪಷ್ಟ',
    outdated: '❌ ಹಳೆಯದು',
    needsReview: 'ℹ ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    current: 'ಪ್ರಸ್ತುತ',
    amended: 'ತಿದ್ದುಪಡಿಯಾಗಿದೆ',
    superseded: 'ಬದಲಾಯಿಸಲಾಗಿದೆ',
    withdrawn: 'ಹಿಂತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ',
    underRevision: 'ಮರುಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    draft: 'ಕರಡು',
    confirmedMatch: '✓ ದೃಢೀಕರಿಸಿದ ಹೋಲಿಕೆ',
    potentialMatch: 'ಸಂಭಾವ್ಯ ಹೋಲಿಕೆ',

    extractedRequirements: 'ಹೊರತೆಗೆಯಲಾದ ಅವಶ್ಯಕತೆಗಳು',
    product: 'ಉತ್ಪನ್ನದ ಹೆಸರು',
    quantity: 'ಪ್ರಮಾಣ',
    capacity: 'ಸಾಮರ್ಥ್ಯ',
    material: 'ವಸ್ತು',
    application: 'ಅಪ್ಲಿಕೇಶನ್',
    otherRequirements: 'ಇತರ ಅವಶ್ಯಕತೆಗಳು',
    confidence: 'ನಂಬಿಕೆ',
    relevance: 'ಸಂಬಂಧಿತತೆ',
    evidenceAndTraceability: 'ಸಾಕ್ಷ್ಯ ಮತ್ತು ಪತ್ತೆಹಚ್ಚುವಿಕೆ',
    parameter: 'ನಿಯತಾಂಕ',
    tenderValue: 'ಟೆಂಡರ್ ಮೌಲ್ಯ',
    standardRequirement: 'ಮಾನದಂಡದ ಅವಶ್ಯಕತೆ',
    status: 'ಸ್ಥಿತಿ',

    responsibleAiNotice: 'ಜವಾಬ್ದಾರಿಯುತ AI ಸೂಚನೆ: IS-SMART ಸೂಚ್ಯಂಕಿತ ಮಾಹಿತಿಯ ಆಧಾರದ ಮೇಲೆ AI ಶಿಫಾರಸುಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ. ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳುವ ಮೊದಲು ಅಧಿಕೃತ BIS ಪ್ರಕಟಣೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.',
  },

  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    analyzeReq: 'ആവശ്യകത വിശകലനം ചെയ്യുക',
    tenderAnalyzer: 'ടെൻഡർ അനലൈസർ',
    specAssistant: 'സ്പെസിഫിക്കേഷൻ അസിസ്റ്റന്റ്',
    standardsExplorer: 'സ്റ്റാൻഡേർഡ് എക്സ്പ്ലോറർ',
    standardsGraph: 'സ്റ്റാൻഡേർഡ് ഗ്രാഫ്',
    gapAnalysis: 'ഗ്യാപ് അനാലിസിസ്',
    versionCheck: 'പതിപ്പും ഭേദഗതികളും',
    certification: 'സർട്ടിഫിക്കേഷൻ',
    analysisHistory: 'വിശകലന ചരിത്രം',
    howItWorks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    about: 'ഞങ്ങളെക്കുറിച്ച്',
    searchPlaceholder: 'മാനദണ്ഡങ്ങൾ, ഉൽപ്പന്നങ്ങൾ തിരയുക...',
    askIsSmart: 'IS-SMART-നോട് ചോദിക്കുക',
    systemStatus: 'സിസ്റ്റം നില',
    allOperational: 'എല്ലാ സിസ്റ്റങ്ങളും പ്രവർത്തിക്കുന്നു',

    aiStandardsIntel: 'AI അധിഷ്ഠിത ഇന്ത്യൻ സ്റ്റാൻഡേർഡ്സ് ഇന്റലിജൻസ്',
    heroTitlePart1: 'ശരിയായ ',
    indianStandards: 'ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ',
    heroTitlePart2: ' കണ്ടെത്തുക. മികച്ച ടെൻഡറുകൾ നിർമ്മിക്കുക.',
    heroSubtitle: 'സംഭരണം, ടെൻഡർ സ്പെസിഫിക്കേഷൻ, കംപ്ലയൻസ് അവലോകനം എന്നിവയ്ക്കുള്ള AI-അധിഷ്ഠിത ഇന്ത്യൻ മാനദണ്ഡങ്ങൾ ഇന്റലിജൻസ്.',
    startAnalysis: 'വിശകലനം ആരംഭിക്കുക',
    exploreStandards: 'മാനദണ്ഡങ്ങൾ പര്യവേക്ഷണം ചെയ്യുക',
    procurementPlaceholder: 'നിങ്ങളുടെ സംഭരണ ആവശ്യകത വിശദമായി വിവരിക്കുക... ഉദാഹരണത്തിന്: സർക്കാർ ആശുപത്രികൾക്കായി 750 ലിറ്റർ ശേഷിയുള്ള 500 സ്റ്റെയിൻലെസ്സ് സ്റ്റീൽ വാട്ടർ ടാങ്കുകൾ വാങ്ങുക',
    uploadTenderDoc: 'ടെൻഡർ രേഖ അപ്‌ലോഡ് ചെയ്യുക',

    projectWorkspace: 'പ്രൊജക്റ്റ് ഇൻപുട്ട് വർക്ക്സ്പേസ്',
    noActiveProject: 'സജീവമായ പ്രൊജക്റ്റ് ഇല്ല',
    createProject: 'പ്രൊജക്റ്റ് സൃഷ്ടിക്കുക',
    createNewProject: 'പുതിയ പ്രൊജക്റ്റ് സൃഷ്ടിക്കുക',
    editProject: 'പ്രൊജക്റ്റ് എഡിറ്റ് ചെയ്യുക',
    projectName: 'പ്രൊജക്റ്റിന്റെ പേര്',
    tenderTextLabel: 'ടെൻഡർ / സാങ്കേതിക ആവശ്യകത ടെക്സ്റ്റ്',
    pasteTenderText: 'ടെൻഡർ ടെക്സ്റ്റ് പേസ്റ്റ് ചെയ്യുക',
    loadPresetExample: '⚡ മുൻകൂട്ടി നിർവ്വചിച്ച ഉദാഹരണം ലോഡ് ചെയ്യുക...',
    saveAndActivate: 'സേവ് ചെയ്ത് ആക്റ്റീവ് ആക്കുക',
    saveChanges: 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
    cancel: 'റദ്ദാക്കുക',
    save: 'സേവ് ചെയ്യുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    delete: 'ഡിലീറ്റ് ചെയ്യുക',
    upload: 'അപ്‌ലോഡ് ചെയ്യുക',
    search: 'തിരയുക',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    processing: 'പ്രോസസ്സ് ചെയ്യുന്നു...',
    confirm: 'ആവശ്യകതകൾ സ്ഥിരീകരിക്കുക',
    findStandards: 'മാനദണ്ഡങ്ങൾ കണ്ടെത്തുക',
    runAnalysis: 'വിശകലനം ചെയ്യുക',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    viewSource: 'ഉറവിടം കാണുക',
    copyEvidence: 'തെളിവ് കോപ്പി ചെയ്യുക',
    whyThisStandard: 'എന്തുകൊണ്ട് ഈ മാനദണ്ഡം?',
    viewEvidence: 'തെളിവുകൾ കാണുക',
    relatedStandards: 'ബന്ധപ്പെട്ട മാനദണ്ഡങ്ങൾ',

    standardsIndexed: 'ഇൻഡക്സ് ചെയ്ത മാനദണ്ഡങ്ങൾ',
    acrossAllSectors: 'എല്ലാ മേഖലകളിലും',
    relationshipsMapped: 'മാപ്പ് ചെയ്ത ബന്ധങ്ങൾ',
    standardsInterconnections: 'മാനദണ്ഡങ്ങളുടെ ബന്ധങ്ങൾ',
    tendersAnalyzed: 'വിശകലനം ചെയ്ത ടെൻഡറുകൾ',
    thisMonth: 'ഈ മാസം',
    issuesDetected: 'കണ്ടെത്തിയ പ്രശ്നങ്ങൾ',
    potentialSpecGaps: 'സാധ്യമായ സ്പെസിഫിക്കേഷൻ ഇടവേളകൾ',
    aiAnalysisPipeline: 'AI വിശകലന പൈപ്പ്ലൈൻ',
    recentAnalyses: 'സമീപകാല വിശകലനങ്ങൾ',
    topStandardsByUsage: 'ഉപയോഗത്തിൽ മുന്നിലുള്ള മാനദണ്ഡങ്ങൾ',
    issueSummary: 'പ്രശ്നങ്ങളുടെ സംഗ്രഹം',
    totalIssues: 'ആകെ പ്രശ്നങ്ങൾ',

    match: '✓ പൊരുത്തപ്പെടുന്നു',
    missing: '⚠ ലഭ്യമല്ല',
    ambiguous: '⚠ അവ്യക്തം',
    outdated: '❌ കാലഹരണപ്പെട്ടത്',
    needsReview: 'ℹ അവലോകനം ആവശ്യമാണ്',
    completed: 'പൂർത്തിയായി',
    current: 'നിലവിലുള്ളത്',
    amended: 'ഭേദഗതി വരുത്തിയത്',
    superseded: 'മാറ്റിസ്ഥാപിക്കപ്പെട്ടു',
    withdrawn: 'പിൻവലിക്കപ്പെട്ടു',
    underRevision: 'അവലോകനത്തിൽ',
    draft: 'കരട്',
    confirmedMatch: '✓ സ്ഥിരീകരിച്ച പൊരുത്തം',
    potentialMatch: 'സാധ്യമായ പൊരുത്തം',

    extractedRequirements: 'വേർതിരിച്ചെടുത്ത ആവശ്യകതകൾ',
    product: 'ഉൽപ്പന്നത്തിന്റെ പേര്',
    quantity: 'അളവ്',
    capacity: 'ശേഷി',
    material: 'മെറ്റീരിയൽ',
    application: 'ആപ്ലിക്കേഷൻ',
    otherRequirements: 'മറ്റ് ആവശ്യകതകൾ',
    confidence: 'വിശ്വാസ്യത',
    relevance: 'പൊരുത്തം',
    evidenceAndTraceability: 'തെളിവുകളും വിശകലനവും',
    parameter: 'പാരാമീറ്റർ',
    tenderValue: 'ടെൻഡർ മൂല്യം',
    standardRequirement: 'മാനദണ്ഡ ആവശ്യകത',
    status: 'നില',

    responsibleAiNotice: 'ഉത്തരവാദിത്തമുള്ള AI അറിയിപ്പ്: IS-SMART ഇൻഡക്സ് ചെയ്ത വിവരങ്ങളുടെ അടിസ്ഥാനത്തിൽ AI ശുപാർശകൾ നൽകുന്നു. തീരുമാനങ്ങൾ എടുക്കുന്നതിന് മുമ്പ് ഔദ്യോഗിക BIS പ്രസിദ്ധീകരണങ്ങൾ ഉറപ്പാക്കുക.',
  },
};

// ── Language Context Setup ───────────────────────────────────────────────────
interface LanguageContextValue {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
});

const STORAGE_KEY = 'is-smart-language';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('en');

  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY) as LangCode | null;
      if (stored && LANGUAGES.find((l) => l.code === stored)) {
        setLangState(stored);
        document.documentElement.lang = stored;
      } else {
        setLangState('en');
        document.documentElement.lang = 'en';
      }
    } catch {
      setLangState('en');
      document.documentElement.lang = 'en';
    }
  }, []);

  function setLang(code: LangCode) {
    setLangState(code);
    document.documentElement.lang = code;
    try {
      localStorage.setItem(STORAGE_KEY, code);
    } catch {}
  }

  function t(key: string): string {
    return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
